### ISSUE TITLE
Orientation issue 

### ISSUE THREAD

**Issue by rajeshkumar-l-2098** [dineshjoker/ListOfUser#3]
Detail page does not support Landsacape.

**Comment by rajeshkumar-l-2098** [comment]
![img_9466](https://user-images.githubusercontent.com/4270930/41964324-4d2bd5d6-7a17-11e8-9539-012d2c10e418.PNG)
Image not look good.

**Comment by dineshjoker** [comment]
sorry sir now it's fixed and updated.

Thankyou,
Dinesh.M

**Comment by dineshjoker** [comment]
Hi sir,

        Should not load all page data Initially. #4. This issue is fixed
sir.

Thankyou,
Dinesh.M
